name: Release test ESP-IDF

on:
  workflow_call:
    inputs:
      idf_target:
        required: true
        type: string
      coap_gateway_url:
        required: true
        type: string

jobs:
  rand_name:
    runs-on: ubuntu-latest
    name: esp-idf-device-name

    outputs:
      device_name: ${{ steps.generate-name.outputs.device_name }}

    steps:
      - name: Generate device name
        id: generate-name
        shell: python
        run: |
          import random
          import os
          import string

          random_string = ''.join(random.choice(string.ascii_lowercase + string.digits)
                                  for _ in range(16))

          device_name = f'esp-idf-{random_string}'
          print(f"Device name is: {device_name}")

          with open(os.environ['GITHUB_OUTPUT'], 'a') as github_output:
            print(f'device_name={device_name}', file=github_output)

  build:
    name: Build ESP-IDF certificate-auth
    runs-on: ubuntu-latest
    needs: rand_name

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prep for build
        id: build_prep
        run: |
          rm -rf test_binaries
          mkdir test_binaries

      - name: Generate certificates
        env:
          DEVICE_NAME: ${{ needs.rand_name.outputs.device_name }}
        shell: bash
        run: |
          scripts/certificates/generate_root_certificate.sh
          scripts/certificates/generate_device_certificate.sh "ci" "$DEVICE_NAME" pem

      - name: Stage certificates
        run: |
          mkdir examples/esp_idf/certificate_auth/main/certs
          mv golioth.crt.pem examples/esp_idf/certificate_auth/main/certs/.
          mv golioth.key.pem examples/esp_idf/certificate_auth/main/certs/.
          mv *.crt.pem examples/esp_idf/certificate_auth/main/certs/client.crt.pem
          mv *.key.pem examples/esp_idf/certificate_auth/main/certs/client.key.pem

      - name: Build Samples
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: ${{ inputs.idf_target }}
          command: |
            echo CONFIG_GOLIOTH_COAP_HOST_URI=\"${{ inputs.coap_gateway_url }}\" \
              >> examples/esp_idf/certificate_auth/sdkconfig.defaults && \
              idf.py -C examples/esp_idf/certificate_auth/ build
            done

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-binary-${{ inputs.idf_target }}
          path: examples/esp_idf/certificate_auth/build/merged.bin

