name: "Test: Comprehensive"

on:
  workflow_dispatch:
    inputs:
      api-url:
        description: "API gateway URL for Golioth backend services"
        required: false
        default: "https://api.golioth.io"
      api-key-id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        default: "PROD_CI_PROJECT_API_KEY"
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        default: "coaps://coap.golioth.io"
      workflow:
        description: "Select which workflow to run"
        required: false
        type: choice
        default: 'all'
        options:
          - all
          - zephyr_integration
          - zephyr_integration_native_sim
          - zephyr_sample
          - zephyr_sample_native_sim
          - esp_idf_integration
          - esp_idf_sample
          - linux_integration
      allure_branch:
        description: "Override the branch selected to store Allure reports"
        required: false
        type: choice
        default: 'auto'
        options:
          - auto
          - main
          - branch
          - recurring

  workflow_call:
    inputs:
      api-url:
        description: "API gateway URL for Golioth backend services"
        required: false
        type: string
        default: "https://api.golioth.io"
      api-key-id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        type: string
        default: "PROD_CI_PROJECT_API_KEY"
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        type: string
        default: "coaps://coap.golioth.io"
      workflow:
        description: "Select which workflow to run"
        required: false
        type: string
        default: 'all'
      allure_branch:
        description: "Override the branch selected to store Allure reports"
        required: false
        type: string
        default: 'auto'

jobs:
  hil_sample_zephyr:
    if: ${{ inputs.workflow == 'all' || inputs.workflow == 'zephyr_sample' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - hil_board: esp32_devkitc_wrover
            west_board: esp32_devkitc_wrover/esp32/procpu
            manifest: .ci-west-zephyr.yml
            extra_twister_args: >-
              --flash-before
              --west-flash=--esp-tool=$(which esptool.py),--esp-device=${!PORT_VAR}
            binary_blob: hal_espressif
            run_tests: true
    uses: ./.github/workflows/hil-sample-zephyr.yml
    with:
      hil_board: ${{ matrix.hil_board }}
      west_board: ${{ matrix.west_board }}
      manifest: ${{ matrix.manifest }}
      binary_blob: ${{ matrix.binary_blob }}
      run_tests: ${{ matrix.run_tests }}
      extra_twister_args: ${{ matrix.extra_twister_args }}
      api-url: ${{ inputs.api-url }}
      api-key-id: ${{ inputs.api-key-id }}
      coap_gateway_url: ${{ inputs.coap_gateway_url }}
    secrets: inherit
