name: Tests

on:
  push:

jobs:
  hil_sample_esp-idf:
    strategy:
      fail-fast: false
      matrix:
        include:
          - hil_board: esp32s3_devkitc
            idf_target: esp32s3
          - hil_board: esp32_devkitc_wrover
            idf_target: esp32
          - hil_board: esp32c3_devkitm
            idf_target: esp32c3
    uses: ./.github/workflows/release_test_esp-idf.yml
    with:
      idf_target: ${{ matrix.idf_target }}
      #coap_gateway_url: ${{ inputs.coap_gateway_url }}
      coap_gateway_url: "coaps://coap.golioth.io"
    secrets: inherit
