name: "Test: Comprehensive"

on:
  workflow_dispatch:
    inputs:
      api-url:
        description: "API gateway URL for Golioth backend services"
        required: false
        default: "https://api.golioth.io"
      api-key-id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        default: "PROD_CI_PROJECT_API_KEY"
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        default: "coaps://coap.golioth.io"
      workflow:
        description: "Select which workflow to run"
        required: false
        type: choice
        default: 'all'
        options:
          - all
          - zephyr_integration
          - zephyr_integration_native_sim
          - zephyr_sample
          - zephyr_sample_native_sim
          - esp_idf_integration
          - esp_idf_sample
          - linux_integration
      allure_branch:
        description: "Override the branch selected to store Allure reports"
        required: false
        type: choice
        default: 'auto'
        options:
          - auto
          - main
          - branch
          - recurring

  workflow_call:
    inputs:
      api-url:
        description: "API gateway URL for Golioth backend services"
        required: false
        type: string
        default: "https://api.golioth.io"
      api-key-id:
        description: >-
          Name of GitHub secret containing an API key that will be used to authenticate with the
          Golioth backend
        required: false
        type: string
        default: "PROD_CI_PROJECT_API_KEY"
      coap_gateway_url:
        description: "The CoAP gateway URL to be hardcoded into test firmware"
        required: false
        type: string
        default: "coaps://coap.golioth.io"
      workflow:
        description: "Select which workflow to run"
        required: false
        type: string
        default: 'all'
      allure_branch:
        description: "Override the branch selected to store Allure reports"
        required: false
        type: string
        default: 'auto'

jobs:
  hil_sample_zephyr:
    if: ${{ inputs.workflow == 'all' || inputs.workflow == 'zephyr_sample' }}
    strategy:
      fail-fast: false
      matrix:
        runner_name: [mikes_testbench, tims_orange_pi, mikes_orange_pi, sams_orange_pi]
    uses: ./.github/workflows/hil-sample-zephyr.yml
    with:
      hil_board: esp32_devkitc_wrover
      west_board: esp32_devkitc_wrover/esp32/procpu
      manifest: .ci-west-zephyr.yml
      binary_blob: hal_espressif
      run_tests: true
      extra_twister_args: >-
        --flash-before
        --west-flash=--esp-tool=$(which esptool.py),--esp-device=${!PORT_VAR}
      api-url: ${{ inputs.api-url }}
      api-key-id: ${{ inputs.api-key-id }}
      coap_gateway_url: ${{ inputs.coap_gateway_url }}
      runner_name: ${{ matrix.runner_name }}
    secrets: inherit
